### ISSUE TITLE
Is there a live demonstration of the transcription?

### ISSUE THREAD

**Issue by mateo-vial** [Yujia-Yan/Skipping-The-Frame-Level#2]
Hi and thanks for releasing the code. The title speaks for itself. I'd like to know if there is a demonstration of a music being transcribed by that algorithm.

**Comment by Yujia-Yan** [comment]
Sorry for answering this issues so late. Let me assume the demonstration you are asking is midi or audio. Here it is the transcribed midi and resynthsized audio for https://www.youtube.com/watch?v=0Ucdew8O-mA:  https://drive.google.com/drive/folders/1TJK4e3QoeUy9h-lIwUEdHa4knuQGi41Q?usp=sharing

**Comment by mateo-vial** [comment]
Awesome, it's exactly what I was looking for. Thanks!
