### ISSUE TITLE
The facility and the time it takes to train the model?

### ISSUE THREAD

**Issue by pangtouyuqqq** [Yujia-Yan/Skipping-The-Frame-Level#6]
Hello, thank you for opening source your marvelous work ~! 
I am curious about the facility (how many GPUs) and the time it takes to train the model.

**Comment by Yujia-Yan** [comment]
This work was done on 2 x 1080 ti gpu. It ran for around 4 days (maybe). But actually flexible: the point to use OneCycleLR (https://arxiv.org/abs/1708.07120) is that it looks like it can give you somewhat faster convergence when you have a fixed time budget to train. I believe it can be trained faster if larger max learning rate and smaller total steps were set. 

https://github.com/Yujia-Yan/Skipping-The-Frame-Level/blob/29b8cce8b414df9cf9b4e75237ae08f0d1a1eecc/transkun/TrainUtil.py#L128

**Comment by pangtouyuqqq** [comment]
Got it, thank you ~!
