### ISSUE TITLE
About the model size

### ISSUE THREAD

**Issue by pangtouyuqqq** [Yujia-Yan/Skipping-The-Frame-Level#8]
Hello, I have a question about the **model size**.
The pretrained model you gave is 40MB (https://github.com/Yujia-Yan/Skipping-The-Frame-Level/tree/main/transkun/pretrained)
But when I run the training script using this [config](https://github.com/Yujia-Yan/Skipping-The-Frame-Level/blob/main/transkun/Model_ablation.py#L16), I got a checkpoint which is 170MB.

**Comment by Yujia-Yan** [comment]
The provided one is only 1 * model size.

Let's break down what's needed to save the state during training:
1. current model: 1* model size
2. best model: 1* model size
3. Adam kind of optimizer: 2 * model size

So during training it's 4 times the model size.

**Comment by pangtouyuqqq** [comment]
Got it~! Thank you
